#!/usr/bin/env bash
#Installing nginx on a web server

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html
service nginx restart






















