#!/usr/bin/env bash
#Installing nginx on a web server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start






















