#!/usr/bin/env bash
#Configuring nginx to listen on port 80

#Removing default configuration file
rm /etc/nginx/sites-available/default
#configure ngnix to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restarting nginx
service nginx restart
