#!/usr/bin/env bash
#while if conditions
#if condition to check if i equal to 8

i=0
while [ $i -lt 10 ]
do
  if [ $i -eq 8 ]
  then
    echo "Hi"
    (( i++ ))
  fi
  echo "Best School"
  (( i++ ))
done
